### ISSUE TITLE
Unhandled Exception: RangeError (index): Invalid value: Not in range 0..53, inclusive: 54

### ISSUE THREAD

**Issue by JDChi** [mdg-soc-19/explode-view#5]
When I clone the project and run , it throws the error :
>  [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: RangeError (index): Invalid value: Not in range 0..53, inclusive: 54
E/flutter ( 3183): #0      List.[] (dart:core-patch/growable_array.dart:146:60)
E/flutter ( 3183): #1      _ExplodeViewState.build.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:explode_view/explode_view.dart:286:53)
E/flutter ( 3183): #2      new Future.delayed.<anonymous closure> (dart:async/future.dart:318:39)
E/flutter ( 3183): #3      _rootRun (dart:async/zone.dart:1180:38)
E/flutter ( 3183): #4      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 3183): #5      _CustomZone.runGuarded (dart:async/zone.dart:979:7)
E/flutter ( 3183): #6      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
E/flutter ( 3183): #7      _rootRun (dart:async/zone.dart:1184:13)
E/flutter ( 3183): #8      _CustomZone.run (dart:async/zone.dart:1077:19)
E/flutter ( 3183): #9      _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1003:23)
E/flutter ( 3183): #10     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:23:15)
E/flutter ( 3183): #11     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 3183): #12     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 3183): #13     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 3183):

**Comment by hemilpanchiwala** [comment]
@JDNew, the project is running fine on my device. I am not sure what the error is but it can be a screen size error. However, there shouldn't any screen size error also but can you please once check on another phone?
